# Generated by Django 5.0.4 on 2024-05-07 20:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0002_project'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='emp',
        ),
    ]
