# Generated by Django 5.0.4 on 2024-05-08 06:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0005_project_name_alter_project_title'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='deadline',
            new_name='task_deadline',
        ),
        migrations.RenameField(
            model_name='project',
            old_name='description',
            new_name='task_description',
        ),
        migrations.RenameField(
            model_name='project',
            old_name='status',
            new_name='task_status',
        ),
        migrations.RenameField(
            model_name='project',
            old_name='title',
            new_name='task_title',
        ),
    ]
