# Generated by Django 5.0.4 on 2024-05-08 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0006_rename_deadline_project_task_deadline_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='task_description',
            field=models.TextField(null=True),
        ),
    ]
