# Generated by Django 5.0.4 on 2024-05-08 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0007_alter_project_task_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='task_deadline',
            field=models.DateField(null=True),
        ),
    ]
