# Generated by Django 5.0.4 on 2024-05-08 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0008_alter_project_task_deadline'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='task_title',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
