# Generated by Django 5.0.4 on 2024-05-10 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0011_remove_project_user_alter_emp_id_alter_project_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emp',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
